# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AMap3DMap' #3D地图SDK
pod 'AMapSearch' # 搜索服务SDK
